cargo-martian: Fix clippy lint due to missing type annotations with HashMap
The original clippy error:
```
  error[E0282]: type annotations needed for `std::collections::HashMap<K, std::string::String>`
```